use cloud_config;

insert into application_label_version (application, label , profile, version) values ('app1', 'master', 'devel', 45f59300-264c-11e5-a695-9d4a736a4a7c);

insert into application_label_version (application, label , profile, version) values ('app1', 'master', '', 45f59300-264c-11e5-a695-9d4a736a4a7d);

insert into application_label_version (application, label , profile, version) values ('application', 'master', '', 45f59300-264c-11e5-a695-9d4a736a4a7e);

